### ISSUE TITLE
List of words that we _may_ want

### ISSUE THREAD

**Issue by ghost** [openSUSE/suse-documentation-dicts#5]
haven't checked whether these are part of the list yet, via old style guide Trello:

- [x] subdirectory (check styleguide)
- [x] colocation
- [x] colocational
- [x] locational
- [x] DAPS
- [x] SUSEDoc
- [x] SBD
- [x] cmirrord
- [x] unordered
- [x] scalability
- [x] scalable
- [x] systemd
- [x] UI
- [x] resynchronization
- [x] unsynchronized
- [x] crmsh
- [x] LXC
- [x] RRP
- [x] UDPU
- [x] GFS
- [x] URI
- [x] reinvoked
- [x] passwordless (?)
- [x] tunable
- [x] reinstalling
- [x] subvolume
- [x] subvolumes
- [x] unclustered
- [x] interoperate (?)
- [x] uninterruptible
- [x] heartbeating (?)
- [x] switchover
- [x] multipath
- [x] subcommand
- [x] subnetmask
- [x] subset
- [x] subsystem
- [x] subentry

**Comment by dariavladykina** [comment]
All the terms have been added to the new wordlist.
